import type { TableDefinition } from '../../types';

/**
 * Table C1: Geographical designators A1A2 for use in abbreviated headings
 * T1T2A1A2ii CCCC YYGGgg for bulletins containing meteorological information,
 * excluding ships' weather reports and oceanographic data
 *
 * Part I: Country or territory designators
 * Part II: Area designators
 */
export const TABLE_C1: TableDefinition = {
  id: 'C1',
  name: 'Geographical designators A1A2',
  description: 'Country and area designators for meteorological bulletins',
  entries: [
    // Part I - Countries/Territories (alphabetically by code)
    { code: 'AB', label: 'Albania', metadata: { type: 'country', continent: 'EU' } },
    { code: 'AG', label: 'Argentina', metadata: { type: 'country', continent: 'SA' } },
    { code: 'AH', label: 'Afghanistan', metadata: { type: 'country', continent: 'AS' } },
    { code: 'AI', label: 'Ascension Island', metadata: { type: 'territory', continent: 'AF' } },
    { code: 'AJ', label: 'Azerbaijan', metadata: { type: 'country', continent: 'AS' } },
    { code: 'AK', label: 'Alaska', metadata: { type: 'territory', continent: 'NA' } },
    { code: 'AL', label: 'Algeria', metadata: { type: 'country', continent: 'AF' } },
    { code: 'AN', label: 'Angola', metadata: { type: 'country', continent: 'AF' } },
    { code: 'AT', label: 'Antigua and Barbuda, Saint Kitts and Nevis, and other British islands in the vicinity', metadata: { type: 'country', continent: 'CA' } },
    { code: 'AU', label: 'Australia', metadata: { type: 'country', continent: 'OC' } },
    { code: 'AY', label: 'Armenia', metadata: { type: 'country', continent: 'AS' } },
    { code: 'AZ', label: 'Azores', metadata: { type: 'territory', continent: 'EU' } },
    { code: 'BA', label: 'Bahamas', metadata: { type: 'country', continent: 'CA' } },
    { code: 'BC', label: 'Botswana', metadata: { type: 'country', continent: 'AF' } },
    { code: 'BD', label: 'Brunei Darussalam', metadata: { type: 'country', continent: 'AS' } },
    { code: 'BE', label: 'Bermuda', metadata: { type: 'territory', continent: 'NA' } },
    { code: 'BH', label: 'Belize', metadata: { type: 'country', continent: 'CA' } },
    { code: 'BI', label: 'Burundi', metadata: { type: 'country', continent: 'AF' } },
    { code: 'BJ', label: 'Benin', metadata: { type: 'country', continent: 'AF' } },
    { code: 'BK', label: 'Banks Islands', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'BM', label: 'Myanmar', metadata: { type: 'country', continent: 'AS' } },
    { code: 'BN', label: 'Bahrain', metadata: { type: 'country', continent: 'AS' } },
    { code: 'BO', label: 'Bolivia (Plurinational State of)', metadata: { type: 'country', continent: 'SA' } },
    { code: 'BR', label: 'Barbados', metadata: { type: 'country', continent: 'CA' } },
    { code: 'BT', label: 'Bhutan', metadata: { type: 'country', continent: 'AS' } },
    { code: 'BU', label: 'Bulgaria', metadata: { type: 'country', continent: 'EU' } },
    { code: 'BV', label: 'Bouvet Island', metadata: { type: 'territory', continent: 'AN' } },
    { code: 'BW', label: 'Bangladesh', metadata: { type: 'country', continent: 'AS' } },
    { code: 'BX', label: 'Belgium, Luxembourg', metadata: { type: 'country', continent: 'EU' } },
    { code: 'BY', label: 'Belarus', metadata: { type: 'country', continent: 'EU' } },
    { code: 'BZ', label: 'Brazil', metadata: { type: 'country', continent: 'SA' } },
    { code: 'CD', label: 'Chad', metadata: { type: 'country', continent: 'AF' } },
    { code: 'CE', label: 'Central African Republic', metadata: { type: 'country', continent: 'AF' } },
    { code: 'CG', label: 'Congo', metadata: { type: 'country', continent: 'AF' } },
    { code: 'CH', label: 'Chile', metadata: { type: 'country', continent: 'SA' } },
    { code: 'CI', label: 'China', metadata: { type: 'country', continent: 'AS' } },
    { code: 'CM', label: 'Cameroon', metadata: { type: 'country', continent: 'AF' } },
    { code: 'CN', label: 'Canada', metadata: { type: 'country', continent: 'NA' } },
    { code: 'CO', label: 'Colombia', metadata: { type: 'country', continent: 'SA' } },
    { code: 'CR', label: 'Canary Islands (Spain)', metadata: { type: 'territory', continent: 'AF' } },
    { code: 'CS', label: 'Costa Rica', metadata: { type: 'country', continent: 'CA' } },
    { code: 'CT', label: 'Canton Island', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'CU', label: 'Cuba', metadata: { type: 'country', continent: 'CA' } },
    { code: 'CV', label: 'Cabo Verde', metadata: { type: 'country', continent: 'AF' } },
    { code: 'CY', label: 'Cyprus', metadata: { type: 'country', continent: 'EU' } },
    { code: 'CZ', label: 'Czechia', metadata: { type: 'country', continent: 'EU' } },
    { code: 'DC', label: 'Bonaire, St Eustatius and Saba', metadata: { type: 'territory', continent: 'CA' } },
    { code: 'DJ', label: 'Djibouti', metadata: { type: 'country', continent: 'AF' } },
    { code: 'DL', label: 'Germany', metadata: { type: 'country', continent: 'EU' } },
    { code: 'DN', label: 'Denmark', metadata: { type: 'country', continent: 'EU' } },
    { code: 'DO', label: 'Dominica', metadata: { type: 'country', continent: 'CA' } },
    { code: 'DR', label: 'Dominican Republic', metadata: { type: 'country', continent: 'CA' } },
    { code: 'EG', label: 'Egypt', metadata: { type: 'country', continent: 'AF' } },
    { code: 'EI', label: 'Eritrea', metadata: { type: 'country', continent: 'AF' } },
    { code: 'EO', label: 'Estonia', metadata: { type: 'country', continent: 'EU' } },
    { code: 'EQ', label: 'Ecuador', metadata: { type: 'country', continent: 'SA' } },
    { code: 'ER', label: 'United Arab Emirates', metadata: { type: 'country', continent: 'AS' } },
    { code: 'ES', label: 'El Salvador', metadata: { type: 'country', continent: 'CA' } },
    { code: 'ET', label: 'Ethiopia', metadata: { type: 'country', continent: 'AF' } },
    { code: 'FA', label: 'Faroe Islands', metadata: { type: 'territory', continent: 'EU' } },
    { code: 'FG', label: 'French Guiana', metadata: { type: 'territory', continent: 'SA' } },
    { code: 'FI', label: 'Finland', metadata: { type: 'country', continent: 'EU' } },
    { code: 'FJ', label: 'Fiji', metadata: { type: 'country', continent: 'OC' } },
    { code: 'FK', label: 'Falkland Islands (Malvinas)', metadata: { type: 'territory', continent: 'SA' } },
    { code: 'FM', label: 'Federated States of Micronesia', metadata: { type: 'country', continent: 'OC' } },
    { code: 'FP', label: 'Saint Pierre and Miquelon', metadata: { type: 'territory', continent: 'NA' } },
    { code: 'FR', label: 'France', metadata: { type: 'country', continent: 'EU' } },
    { code: 'FW', label: 'Wallis and Futuna', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'GB', label: 'Gambia', metadata: { type: 'country', continent: 'AF' } },
    { code: 'GC', label: 'Cayman Islands', metadata: { type: 'territory', continent: 'CA' } },
    { code: 'GD', label: 'Grenada', metadata: { type: 'country', continent: 'CA' } },
    { code: 'GE', label: 'Gough Island', metadata: { type: 'territory', continent: 'AF' } },
    { code: 'GG', label: 'Georgia', metadata: { type: 'country', continent: 'AS' } },
    { code: 'GH', label: 'Ghana', metadata: { type: 'country', continent: 'AF' } },
    { code: 'GI', label: 'Gibraltar', metadata: { type: 'territory', continent: 'EU' } },
    { code: 'GL', label: 'Greenland', metadata: { type: 'territory', continent: 'NA' } },
    { code: 'GM', label: 'Guam', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'GN', label: 'Guinea', metadata: { type: 'country', continent: 'AF' } },
    { code: 'GO', label: 'Gabon', metadata: { type: 'country', continent: 'AF' } },
    { code: 'GQ', label: 'Equatorial Guinea', metadata: { type: 'country', continent: 'AF' } },
    { code: 'GR', label: 'Greece', metadata: { type: 'country', continent: 'EU' } },
    { code: 'GU', label: 'Guatemala', metadata: { type: 'country', continent: 'CA' } },
    { code: 'GW', label: 'Guinea-Bissau', metadata: { type: 'country', continent: 'AF' } },
    { code: 'GY', label: 'Guyana', metadata: { type: 'country', continent: 'SA' } },
    { code: 'HA', label: 'Haiti', metadata: { type: 'country', continent: 'CA' } },
    { code: 'HE', label: 'Saint Helena', metadata: { type: 'territory', continent: 'AF' } },
    { code: 'HK', label: 'Hong Kong, China', metadata: { type: 'territory', continent: 'AS' } },
    { code: 'HO', label: 'Honduras', metadata: { type: 'country', continent: 'CA' } },
    { code: 'HU', label: 'Hungary', metadata: { type: 'country', continent: 'EU' } },
    { code: 'HV', label: 'Burkina Faso', metadata: { type: 'country', continent: 'AF' } },
    { code: 'HW', label: 'Hawaiian Islands', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'IC', label: 'Comoros', metadata: { type: 'country', continent: 'AF' } },
    { code: 'ID', label: 'Indonesia', metadata: { type: 'country', continent: 'AS' } },
    { code: 'IE', label: 'Ireland', metadata: { type: 'country', continent: 'EU' } },
    { code: 'IL', label: 'Iceland', metadata: { type: 'country', continent: 'EU' } },
    { code: 'IN', label: 'India', metadata: { type: 'country', continent: 'AS' } },
    { code: 'IQ', label: 'Iraq', metadata: { type: 'country', continent: 'AS' } },
    { code: 'IR', label: 'Islamic Republic of Iran', metadata: { type: 'country', continent: 'AS' } },
    { code: 'IS', label: 'Israel', metadata: { type: 'country', continent: 'AS' } },
    { code: 'IV', label: "Cote d'Ivoire", metadata: { type: 'country', continent: 'AF' } },
    { code: 'IY', label: 'Italy', metadata: { type: 'country', continent: 'EU' } },
    { code: 'JD', label: 'Jordan', metadata: { type: 'country', continent: 'AS' } },
    { code: 'JM', label: 'Jamaica', metadata: { type: 'country', continent: 'CA' } },
    { code: 'JP', label: 'Japan', metadata: { type: 'country', continent: 'AS' } },
    { code: 'KA', label: 'Caroline Islands', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'KB', label: 'Kiribati', metadata: { type: 'country', continent: 'OC' } },
    { code: 'KI', label: 'Christmas Island', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'KK', label: 'Cocos Islands', metadata: { type: 'territory', continent: 'AS' } },
    { code: 'KN', label: 'Kenya', metadata: { type: 'country', continent: 'AF' } },
    { code: 'KO', label: 'Republic of Korea', metadata: { type: 'country', continent: 'AS' } },
    { code: 'KP', label: 'Cambodia', metadata: { type: 'country', continent: 'AS' } },
    { code: 'KR', label: "Democratic People's Republic of Korea", metadata: { type: 'country', continent: 'AS' } },
    { code: 'KU', label: 'Cook Islands', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'KW', label: 'Kuwait', metadata: { type: 'country', continent: 'AS' } },
    { code: 'KY', label: 'Kyrgyzstan', metadata: { type: 'country', continent: 'AS' } },
    { code: 'KZ', label: 'Kazakhstan', metadata: { type: 'country', continent: 'AS' } },
    { code: 'LA', label: "Lao People's Democratic Republic", metadata: { type: 'country', continent: 'AS' } },
    { code: 'LB', label: 'Lebanon', metadata: { type: 'country', continent: 'AS' } },
    { code: 'LC', label: 'Saint Lucia', metadata: { type: 'country', continent: 'CA' } },
    { code: 'LI', label: 'Liberia', metadata: { type: 'country', continent: 'AF' } },
    { code: 'LJ', label: 'Slovenia', metadata: { type: 'country', continent: 'EU' } },
    { code: 'LN', label: 'Southern Line Islands', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'LS', label: 'Lesotho', metadata: { type: 'country', continent: 'AF' } },
    { code: 'LT', label: 'Lithuania', metadata: { type: 'country', continent: 'EU' } },
    { code: 'LV', label: 'Latvia', metadata: { type: 'country', continent: 'EU' } },
    { code: 'LY', label: 'Libya', metadata: { type: 'country', continent: 'AF' } },
    { code: 'MA', label: 'Mauritius', metadata: { type: 'country', continent: 'AF' } },
    { code: 'MB', label: 'Marion Island', metadata: { type: 'territory', continent: 'AF' } },
    { code: 'MC', label: 'Morocco', metadata: { type: 'country', continent: 'AF' } },
    { code: 'MD', label: 'Madeira', metadata: { type: 'territory', continent: 'EU' } },
    { code: 'MF', label: 'Saint-Martin, Saint-Barthelemy, Guadeloupe and other French islands in the vicinity', metadata: { type: 'territory', continent: 'CA' } },
    { code: 'MG', label: 'Madagascar', metadata: { type: 'country', continent: 'AF' } },
    { code: 'MH', label: 'Marshall Islands', metadata: { type: 'country', continent: 'OC' } },
    { code: 'MI', label: 'Mali', metadata: { type: 'country', continent: 'AF' } },
    { code: 'MJ', label: 'The former Yugoslav Republic of Macedonia', metadata: { type: 'country', continent: 'EU' } },
    { code: 'MK', label: 'Montenegro', metadata: { type: 'country', continent: 'EU' } },
    { code: 'ML', label: 'Malta', metadata: { type: 'country', continent: 'EU' } },
    { code: 'MN', label: 'St Maarten', metadata: { type: 'territory', continent: 'CA' } },
    { code: 'MO', label: 'Mongolia', metadata: { type: 'country', continent: 'AS' } },
    { code: 'MR', label: 'Martinique', metadata: { type: 'territory', continent: 'CA' } },
    { code: 'MS', label: 'Malaysia', metadata: { type: 'country', continent: 'AS' } },
    { code: 'MT', label: 'Mauritania', metadata: { type: 'country', continent: 'AF' } },
    { code: 'MU', label: 'Macao, China', metadata: { type: 'territory', continent: 'AS' } },
    { code: 'MV', label: 'Maldives', metadata: { type: 'country', continent: 'AS' } },
    { code: 'MW', label: 'Malawi', metadata: { type: 'country', continent: 'AF' } },
    { code: 'MX', label: 'Mexico', metadata: { type: 'country', continent: 'NA' } },
    { code: 'MY', label: 'Mariana Islands', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'MZ', label: 'Mozambique', metadata: { type: 'country', continent: 'AF' } },
    { code: 'NC', label: 'New Caledonia', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'NE', label: 'Niue', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'NG', label: 'Papua New Guinea', metadata: { type: 'country', continent: 'OC' } },
    { code: 'NI', label: 'Nigeria', metadata: { type: 'country', continent: 'AF' } },
    { code: 'NK', label: 'Nicaragua', metadata: { type: 'country', continent: 'CA' } },
    { code: 'NL', label: 'Netherlands', metadata: { type: 'country', continent: 'EU' } },
    { code: 'NM', label: 'Namibia', metadata: { type: 'country', continent: 'AF' } },
    { code: 'NO', label: 'Norway', metadata: { type: 'country', continent: 'EU' } },
    { code: 'NP', label: 'Nepal', metadata: { type: 'country', continent: 'AS' } },
    { code: 'NR', label: 'Niger', metadata: { type: 'country', continent: 'AF' } },
    { code: 'NU', label: 'Curacao and Aruba', metadata: { type: 'territory', continent: 'CA' } },
    { code: 'NV', label: 'Vanuatu', metadata: { type: 'country', continent: 'OC' } },
    { code: 'NW', label: 'Nauru', metadata: { type: 'country', continent: 'OC' } },
    { code: 'NZ', label: 'New Zealand', metadata: { type: 'country', continent: 'OC' } },
    { code: 'OM', label: 'Oman', metadata: { type: 'country', continent: 'AS' } },
    { code: 'OO', label: 'Monaco', metadata: { type: 'country', continent: 'EU' } },
    { code: 'OR', label: 'South Orkney Islands', metadata: { type: 'territory', continent: 'AN' } },
    { code: 'OS', label: 'Austria', metadata: { type: 'country', continent: 'EU' } },
    { code: 'PF', label: 'French Polynesia', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'PH', label: 'Philippines', metadata: { type: 'country', continent: 'AS' } },
    { code: 'PI', label: 'Phoenix Islands', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'PK', label: 'Pakistan', metadata: { type: 'country', continent: 'AS' } },
    { code: 'PL', label: 'Poland', metadata: { type: 'country', continent: 'EU' } },
    { code: 'PM', label: 'Panama', metadata: { type: 'country', continent: 'CA' } },
    { code: 'PO', label: 'Portugal', metadata: { type: 'country', continent: 'EU' } },
    { code: 'PP', label: 'Palau', metadata: { type: 'country', continent: 'OC' } },
    { code: 'PR', label: 'Peru', metadata: { type: 'country', continent: 'SA' } },
    { code: 'PT', label: 'Pitcairn', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'PU', label: 'Puerto Rico', metadata: { type: 'territory', continent: 'CA' } },
    { code: 'PY', label: 'Paraguay', metadata: { type: 'country', continent: 'SA' } },
    { code: 'QB', label: 'Bosnia and Herzegovina', metadata: { type: 'country', continent: 'EU' } },
    { code: 'QT', label: 'Qatar', metadata: { type: 'country', continent: 'AS' } },
    { code: 'RA', label: 'Russian Federation (East)', metadata: { type: 'country', continent: 'AS' } },
    { code: 'RE', label: 'Reunion and associated islands', metadata: { type: 'territory', continent: 'AF' } },
    { code: 'RH', label: 'Croatia', metadata: { type: 'country', continent: 'EU' } },
    { code: 'RM', label: 'Republic of Moldova', metadata: { type: 'country', continent: 'EU' } },
    { code: 'RO', label: 'Romania', metadata: { type: 'country', continent: 'EU' } },
    { code: 'RS', label: 'Russian Federation (West)', metadata: { type: 'country', continent: 'EU' } },
    { code: 'RW', label: 'Rwanda', metadata: { type: 'country', continent: 'AF' } },
    { code: 'SB', label: 'Sri Lanka', metadata: { type: 'country', continent: 'AS' } },
    { code: 'SC', label: 'Seychelles', metadata: { type: 'country', continent: 'AF' } },
    { code: 'SD', label: 'Saudi Arabia', metadata: { type: 'country', continent: 'AS' } },
    { code: 'SG', label: 'Senegal', metadata: { type: 'country', continent: 'AF' } },
    { code: 'SI', label: 'Somalia', metadata: { type: 'country', continent: 'AF' } },
    { code: 'SK', label: 'Sarawak', metadata: { type: 'territory', continent: 'AS' } },
    { code: 'SL', label: 'Sierra Leone', metadata: { type: 'country', continent: 'AF' } },
    { code: 'SM', label: 'Suriname', metadata: { type: 'country', continent: 'SA' } },
    { code: 'SN', label: 'Sweden', metadata: { type: 'country', continent: 'EU' } },
    { code: 'SO', label: 'Solomon Islands', metadata: { type: 'country', continent: 'OC' } },
    { code: 'SP', label: 'Spain', metadata: { type: 'country', continent: 'EU' } },
    { code: 'SQ', label: 'Slovakia', metadata: { type: 'country', continent: 'EU' } },
    { code: 'SR', label: 'Singapore', metadata: { type: 'country', continent: 'AS' } },
    { code: 'SU', label: 'Sudan', metadata: { type: 'country', continent: 'AF' } },
    { code: 'SV', label: 'Swaziland', metadata: { type: 'country', continent: 'AF' } },
    { code: 'SW', label: 'Switzerland', metadata: { type: 'country', continent: 'EU' } },
    { code: 'SX', label: 'Santa Cruz Islands', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'SY', label: 'Syrian Arab Republic', metadata: { type: 'country', continent: 'AS' } },
    { code: 'SZ', label: 'Spitzbergen Islands', metadata: { type: 'territory', continent: 'EU' } },
    { code: 'TA', label: 'Tajikistan', metadata: { type: 'country', continent: 'AS' } },
    { code: 'TC', label: 'Tristan da Cunha', metadata: { type: 'territory', continent: 'AF' } },
    { code: 'TD', label: 'Trinidad and Tobago', metadata: { type: 'country', continent: 'CA' } },
    { code: 'TG', label: 'Togo', metadata: { type: 'country', continent: 'AF' } },
    { code: 'TH', label: 'Thailand', metadata: { type: 'country', continent: 'AS' } },
    { code: 'TI', label: 'Turks and Caicos Islands', metadata: { type: 'territory', continent: 'CA' } },
    { code: 'TK', label: 'Tokelau', metadata: { type: 'territory', continent: 'OC' } },
    { code: 'TM', label: 'Timor-Leste', metadata: { type: 'country', continent: 'AS' } },
    { code: 'TN', label: 'United Republic of Tanzania', metadata: { type: 'country', continent: 'AF' } },
    { code: 'TO', label: 'Tonga', metadata: { type: 'country', continent: 'OC' } },
    { code: 'TP', label: 'Sao Tome and Principe', metadata: { type: 'country', continent: 'AF' } },
    { code: 'TR', label: 'Turkmenistan', metadata: { type: 'country', continent: 'AS' } },
    { code: 'TS', label: 'Tunisia', metadata: { type: 'country', continent: 'AF' } },
    { code: 'TU', label: 'Turkey', metadata: { type: 'country', continent: 'AS' } },
    { code: 'TV', label: 'Tuvalu', metadata: { type: 'country', continent: 'OC' } },
    { code: 'UG', label: 'Uganda', metadata: { type: 'country', continent: 'AF' } },
    { code: 'UK', label: 'United Kingdom of Great Britain and Northern Ireland', metadata: { type: 'country', continent: 'EU' } },
    { code: 'UR', label: 'Ukraine', metadata: { type: 'country', continent: 'EU' } },
    { code: 'US', label: 'United States of America', metadata: { type: 'country', continent: 'NA' } },
    { code: 'UY', label: 'Uruguay', metadata: { type: 'country', continent: 'SA' } },
    { code: 'UZ', label: 'Uzbekistan', metadata: { type: 'country', continent: 'AS' } },
    { code: 'VG', label: 'Saint Vincent and the Grenadines', metadata: { type: 'country', continent: 'CA' } },
    { code: 'VI', label: 'Virgin Islands', metadata: { type: 'territory', continent: 'CA' } },
    { code: 'VN', label: 'Venezuela (Bolivarian Republic of)', metadata: { type: 'country', continent: 'SA' } },
    { code: 'VS', label: 'Viet Nam', metadata: { type: 'country', continent: 'AS' } },
    { code: 'YE', label: 'Yemen', metadata: { type: 'country', continent: 'AS' } },
    { code: 'YG', label: 'Serbia', metadata: { type: 'country', continent: 'EU' } },
    { code: 'ZA', label: 'South Africa', metadata: { type: 'country', continent: 'AF' } },
    { code: 'ZB', label: 'Zambia', metadata: { type: 'country', continent: 'AF' } },
    { code: 'ZM', label: 'Samoa', metadata: { type: 'country', continent: 'OC' } },
    { code: 'ZR', label: 'Democratic Republic of the Congo', metadata: { type: 'country', continent: 'AF' } },
    { code: 'ZS', label: 'South Sudan', metadata: { type: 'country', continent: 'AF' } },
    { code: 'ZW', label: 'Zimbabwe', metadata: { type: 'country', continent: 'AF' } },

    // Part II - Area designators
    { code: 'AA', label: 'Antarctic', metadata: { type: 'area', category: 'polar' } },
    { code: 'AC', label: 'Arctic', metadata: { type: 'area', category: 'polar' } },
    { code: 'AE', label: 'South-East Asia', metadata: { type: 'area', category: 'regional' } },
    { code: 'AF', label: 'Africa', metadata: { type: 'area', category: 'continent' } },
    { code: 'AM', label: 'Central Africa', metadata: { type: 'area', category: 'regional' } },
    { code: 'AO', label: 'West Africa', metadata: { type: 'area', category: 'regional' } },
    { code: 'AP', label: 'Southern Africa', metadata: { type: 'area', category: 'regional' } },
    { code: 'AS', label: 'Asia', metadata: { type: 'area', category: 'continent' } },
    { code: 'AW', label: 'Near East', metadata: { type: 'area', category: 'regional' } },
    { code: 'AX', label: 'Arabian Sea area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'BQ', label: 'Baltic Sea area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'CA', label: 'Caribbean and Central America', metadata: { type: 'area', category: 'regional' } },
    { code: 'EA', label: 'East Africa', metadata: { type: 'area', category: 'regional' } },
    { code: 'EC', label: 'East China Sea area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'EE', label: 'Eastern Europe', metadata: { type: 'area', category: 'regional' } },
    { code: 'EM', label: 'Middle Europe', metadata: { type: 'area', category: 'regional' } },
    { code: 'EN', label: 'Northern Europe', metadata: { type: 'area', category: 'regional' } },
    { code: 'EU', label: 'Europe', metadata: { type: 'area', category: 'continent' } },
    { code: 'EW', label: 'Western Europe', metadata: { type: 'area', category: 'regional' } },
    { code: 'FE', label: 'Far East', metadata: { type: 'area', category: 'regional' } },
    { code: 'GA', label: 'Gulf of Alaska area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'GX', label: 'Gulf of Mexico area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'IO', label: 'Indian Ocean area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'ME', label: 'Eastern Mediterranean area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'MM', label: 'Mediterranean area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'MP', label: 'Central Mediterranean area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'MQ', label: 'Western Mediterranean area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'NA', label: 'North America', metadata: { type: 'area', category: 'continent' } },
    { code: 'NT', label: 'North Atlantic area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'OC', label: 'Oceania', metadata: { type: 'area', category: 'continent' } },
    { code: 'OH', label: 'Sea of Okhotsk', metadata: { type: 'area', category: 'maritime' } },
    { code: 'PA', label: 'Pacific area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'PE', label: 'Persian Gulf area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'PN', label: 'North Pacific area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'PQ', label: 'Western North Pacific', metadata: { type: 'area', category: 'maritime' } },
    { code: 'PS', label: 'South Pacific area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'PW', label: 'Western Pacific area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'PZ', label: 'Eastern Pacific area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'SA', label: 'South America', metadata: { type: 'area', category: 'continent' } },
    { code: 'SE', label: 'Southern Ocean area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'SJ', label: 'Sea of Japan area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'SS', label: 'South China Sea area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'ST', label: 'South Atlantic area', metadata: { type: 'area', category: 'maritime' } },
    { code: 'XE', label: 'Eastern hemisphere', metadata: { type: 'area', category: 'hemisphere' } },
    { code: 'XN', label: 'Northern hemisphere', metadata: { type: 'area', category: 'hemisphere' } },
    { code: 'XS', label: 'Southern hemisphere', metadata: { type: 'area', category: 'hemisphere' } },
    { code: 'XT', label: 'Tropical belt', metadata: { type: 'area', category: 'climatic' } },
    { code: 'XW', label: 'Western hemisphere', metadata: { type: 'area', category: 'hemisphere' } },
    { code: 'XX', label: 'For use when other designators are not appropriate', metadata: { type: 'area', category: 'unspecified' } },
  ],
  groups: [
    { key: 'EU', label: 'Europe', codes: ['AB', 'AZ', 'BU', 'BX', 'BY', 'CY', 'CZ', 'DL', 'DN', 'EO', 'FA', 'FI', 'FR', 'GI', 'GR', 'HU', 'IE', 'IL', 'IY', 'LJ', 'LT', 'LV', 'MD', 'MJ', 'MK', 'ML', 'NL', 'NO', 'OO', 'OS', 'PL', 'PO', 'QB', 'RH', 'RM', 'RO', 'RS', 'SN', 'SP', 'SQ', 'SW', 'SZ', 'UK', 'UR', 'YG'] },
    { key: 'AF', label: 'Africa', codes: ['AI', 'AL', 'AN', 'BC', 'BI', 'BJ', 'CD', 'CE', 'CG', 'CM', 'CR', 'CV', 'DJ', 'EG', 'EI', 'ET', 'GB', 'GE', 'GH', 'GN', 'GO', 'GQ', 'GW', 'HE', 'HV', 'IC', 'IV', 'KN', 'LI', 'LS', 'LY', 'MA', 'MB', 'MC', 'MG', 'MI', 'MT', 'MW', 'MZ', 'NI', 'NM', 'NR', 'RE', 'RW', 'SC', 'SG', 'SI', 'SL', 'SU', 'SV', 'TC', 'TG', 'TN', 'TP', 'TS', 'UG', 'ZA', 'ZB', 'ZR', 'ZS', 'ZW'] },
    { key: 'AS', label: 'Asia', codes: ['AH', 'AJ', 'AY', 'BD', 'BM', 'BN', 'BT', 'BW', 'CI', 'ER', 'GG', 'HK', 'ID', 'IN', 'IQ', 'IR', 'IS', 'JD', 'JP', 'KK', 'KO', 'KP', 'KR', 'KW', 'KY', 'KZ', 'LA', 'LB', 'MO', 'MS', 'MU', 'MV', 'NP', 'OM', 'PH', 'PK', 'QT', 'RA', 'SB', 'SD', 'SK', 'SR', 'SY', 'TA', 'TH', 'TM', 'TR', 'TU', 'UZ', 'VS', 'YE'] },
    { key: 'NA', label: 'North America', codes: ['AK', 'BE', 'CN', 'FP', 'GL', 'MX', 'US'] },
    { key: 'SA', label: 'South America', codes: ['AG', 'BO', 'BZ', 'CH', 'CO', 'EQ', 'FG', 'FK', 'GY', 'PR', 'PY', 'SM', 'UY', 'VN'] },
    { key: 'CA', label: 'Caribbean and Central America', codes: ['AT', 'BA', 'BH', 'BR', 'CS', 'CU', 'DC', 'DO', 'DR', 'ES', 'GC', 'GD', 'GU', 'HA', 'HO', 'JM', 'LC', 'MF', 'MN', 'MR', 'NK', 'NU', 'PM', 'PU', 'TD', 'TI', 'VG', 'VI'] },
    { key: 'OC', label: 'Oceania', codes: ['AU', 'BK', 'CT', 'FJ', 'FM', 'FW', 'GM', 'HW', 'KA', 'KB', 'KI', 'KU', 'LN', 'MH', 'MY', 'NC', 'NE', 'NG', 'NV', 'NW', 'NZ', 'PF', 'PI', 'PP', 'PT', 'SO', 'SX', 'TK', 'TO', 'TV', 'ZM'] },
    { key: 'AN', label: 'Antarctic', codes: ['BV', 'OR'] },
    { key: 'AREA', label: 'Area Designators', codes: ['AA', 'AC', 'AE', 'AF', 'AM', 'AO', 'AP', 'AS', 'AW', 'AX', 'BQ', 'CA', 'EA', 'EC', 'EE', 'EM', 'EN', 'EU', 'EW', 'FE', 'GA', 'GX', 'IO', 'ME', 'MM', 'MP', 'MQ', 'NA', 'NT', 'OC', 'OH', 'PA', 'PE', 'PN', 'PQ', 'PS', 'PW', 'PZ', 'SA', 'SE', 'SJ', 'SS', 'ST', 'XE', 'XN', 'XS', 'XT', 'XW', 'XX'] },
  ]
};

/**
 * Continent labels for grouping
 */
export const CONTINENT_LABELS: Record<string, string> = {
  'EU': 'Europe',
  'AF': 'Africa',
  'AS': 'Asia',
  'NA': 'North America',
  'SA': 'South America',
  'CA': 'Caribbean and Central America',
  'OC': 'Oceania',
  'AN': 'Antarctic',
  'AREA': 'Area Designators',
};
